sudo: required
services:
   - docker

before_install:
  - docker build -t rabeya31/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true rabeya31/react-test npm test

after_success:
  - docker build -t rabeya31/multi-client ./client
  - docker build -t rabeya31/multi-nginx ./nginx
  - docker build -t rabeya31/multi-server ./server
  - docker build -t rabeya31/multi-worker ./worker
    
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
  - docker push rabeya31/multi-client
  - docker push rabeya31/multi-server
  - docker push rabeya31/multi-nginx
  - docker push rabeya31/multi-worker

